angular-animate.js
angular-animate.min.js
angular-animate.min.js.map
angular-cookies.js
angular-cookies.min.js
angular-cookies.min.js.map
angular-csp.css
angular-loader.js
angular-loader.min.js
angular-loader.min.js.map
angular-mocks.js
angular-resource.js
angular-resource.min.js
angular-resource.min.js.map
angular-route.js
angular-route.min.js
angular-route.min.js.map
angular-sanitize.js
angular-sanitize.min.js
angular-sanitize.min.js.map
angular-scenario.js
angular-touch.js
angular-touch.min.js
angular-touch.min.js.map
angular.js
angular.min.js
angular.min.js.map
docs
errors.json
i18n
version.json
version.txt