<?php

//////////////////////////////////////////////////////////////
//===========================================================
// iscripts.php
//===========================================================
// SOFTACULOUS 
// Version : 1.1
// Inspired by the DESIRE to be the BEST OF ALL
// ----------------------------------------------------------
// Started by: Alons
// Date:       10th Jan 2009
// Time:       21:00 hrs
// Site:       http://www.softaculous.com/ (SOFTACULOUS)
// ----------------------------------------------------------
// Please Read the Terms of use at http://www.softaculous.com
// ----------------------------------------------------------
//===========================================================
// (c)Softaculous Inc.
//===========================================================
//////////////////////////////////////////////////////////////

if(!defined('SOFTACULOUS')){

	die('Hacking Attempt');

}

$iscripts = array(1 => array('name' => 'Zikula',
							'softname' => 'zikula',
							'desc' => 'Zikula is a Web Application Toolkit, which allows you to run impressive websites and build powerful online applications.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.3.9'
							),
				2 => array('name' => 'phpBB',
							'softname' => 'phpbb',
							'desc' => 'The most widely used Open Source forum solution
',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '3.1.0'
							),
				3 => array('name' => 'Serendipity',
							'softname' => 's9y',
							'desc' => 'PHP-powered, flexible Blogging/CMS application',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '1.7.8'
							),
				4 => array('name' => 'Noahs Classifieds',
							'softname' => 'noah',
							'desc' => 'The leading classifieds software on the web!',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '3.2.0'
							),
				5 => array('name' => 'Xoops',
							'softname' => 'xoops',
							'desc' => 'Xoops is an easy to use dynamic web content management system written in PHP',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.5.7'
							),
				6 => array('name' => 'ocPortal',
							'softname' => 'ocportal',
							'desc' => 'ocPortal is the website Content Management System (a CMS) for building and maintaining a dynamic website.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '9.0.14'
							),
				8 => array('name' => 'AEF',
							'softname' => 'aef',
							'desc' => 'AEF - Advanced Electron Forum is a free bulletin board software written in PHP and MySQL with loads of features',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.0.9'
							),
				9 => array('name' => 'XMB',
							'softname' => 'xmb',
							'desc' => 'XMB is a lightweight PHP forum software with all the features you need to support a growing community',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.9.11.13'
							),
				11 => array('name' => 'Open Blog',
							'softname' => 'openb',
							'desc' => 'Kick-ass Blog application built using the CodeIgniter PHP Framework',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '1.2.1'
							),
				12 => array('name' => 'Drupal 6',
							'softname' => 'drupal6',
							'desc' => 'Drupal is an open source content management platform',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '6.33'
							),
				13 => array('name' => 'Gallery',
							'softname' => 'gallery',
							'desc' => 'Gallery is an open source web based photo album organizer',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '3.0.9'
							),
				14 => array('name' => 'b2evolution',
							'softname' => 'b2e',
							'desc' => 'b2evolution is a powerful blog tool',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '5.1.2'
							),
				15 => array('name' => 'LifeType',
							'softname' => 'life',
							'desc' => 'LifeType is an open-source blogging platform with support for multiple blogs and users in a single installation',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '1.2.12'
							),
				18 => array('name' => 'Joomla 2.5',
							'softname' => 'joomla16',
							'desc' => 'Joomla is an award-winning CMS, which enables you to build Web sites and powerful online applications',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.5.27'
							),
				19 => array('name' => 'WebCalendar',
							'softname' => 'webcal',
							'desc' => 'WebCalendar is a PHP-based calendar application',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '1.2.7'
							),
				20 => array('name' => 'DokuWiki',
							'softname' => 'doku',
							'desc' => 'DokuWiki is a standards compliant, simple to use Wiki, mainly aimed at creating documentation of any kind.',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '2014-09-29a'
							),
				21 => array('name' => 'Website Baker',
							'softname' => 'baker',
							'desc' => 'Website Baker is a PHP-based Content Management System',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.8.3'
							),
				22 => array('name' => 'sNews',
							'softname' => 'snews',
							'desc' => 'sNews is extremely lightweight, simple and customizable',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.7.1'
							),
				24 => array('name' => 'Geeklog',
							'softname' => 'geeklog',
							'desc' => 'Geeklog is a PHP/MySQL based application for managing dynamic web content.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.1.0'
							),
				25 => array('name' => 'MediaWiki',
							'softname' => 'mw',
							'desc' => 'MediaWiki is a free software wiki package written in PHP, originally for use on Wikipedia',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '1.23.6'
							),
				26 => array('name' => 'WordPress',
							'softname' => 'wp',
							'desc' => 'WordPress is a state-of-the-art publishing platform with a focus on aesthetics, web standards, and usability.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '4.0'
							),
				27 => array('name' => 'Coppermine',
							'softname' => 'cpg',
							'desc' => 'Coppermine is a multi-purpose fully-featured and integrated web picture gallery script written in PHP.',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '1.5.34'
							),
				28 => array('name' => 'TinyWebGallery',
							'softname' => 'twg',
							'desc' => 'TinyWebGallery is a free php based photo album / gallery',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '2.2'
							),
				29 => array('name' => 'dotProject',
							'softname' => 'dotproj',
							'desc' => 'dotProject is a volunteer supported Project Management application',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.1.8'
							),
				30 => array('name' => 'Drupal',
							'softname' => 'drupal',
							'desc' => 'Drupal is an open source content management platform',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '7.32'
							),
				31 => array('name' => 'Mambo',
							'softname' => 'mambo',
							'desc' => 'Mambo is a full-featured content management system',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '4.6.5'
							),
				32 => array('name' => 'PHP-Nuke',
							'softname' => 'phpnuke',
							'desc' => 'It is a CMS that integrates in its inside all the instruments that are used to create, in a broad sense, an information portal.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '8.3.2'
							),
				33 => array('name' => 'Nucleus',
							'softname' => 'nucleus',
							'desc' => 'Nucleus CMS is a flexible and easy to install content management system, aka blog software.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '3.65'
							),
				34 => array('name' => 'Dotclear',
							'softname' => 'dotcl',
							'desc' => 'Dotclear is an open-source web publishing software',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '2.6.4'
							),
				35 => array('name' => 'Textpattern',
							'softname' => 'txtpat',
							'desc' => 'Textpattern is a flexible, elegant and easy-to-use content management system.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '4.5.7'
							),
				36 => array('name' => 'MyBB',
							'softname' => 'mybb',
							'desc' => 'Its the easy to use, multilingual, powerful, feature packed, free forum software',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.8.1'
							),
				37 => array('name' => 'Phorum',
							'softname' => 'phorum',
							'desc' => 'The Original PHP and MySQL Forum Software',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '5.2.19'
							),
				38 => array('name' => 'PunBB',
							'softname' => 'punbb',
							'desc' => 'PunBB is a fast and lightweight PHP-powered discussion board.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.4.2'
							),
				39 => array('name' => 'Piwigo',
							'softname' => 'piwigo',
							'desc' => 'Piwigo is a photo gallery software for the web',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '2.7.1'
							),
				40 => array('name' => 'Pixelpost',
							'softname' => 'pixpost',
							'desc' => 'Pixelpost is an open-source, standards-compliant, multi-lingual, fully extensible photoblog application for the web',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '1.7.3'
							),
				41 => array('name' => 'Zenphoto',
							'softname' => 'zen',
							'desc' => 'a simpler web photo gallery',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '1.4.6'
							),
				43 => array('name' => 'PmWiki',
							'softname' => 'pmwiki',
							'desc' => 'PmWiki is a wiki-based system for collaborative creation and maintenance of websites',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '2.2.69'
							),
				44 => array('name' => 'Tiki Wiki CMS Groupware 9',
							'softname' => 'tiki',
							'desc' => 'Tiki is your Groupware/CMS (Content Management System) solution',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '9.8'
							),
				45 => array('name' => 'Revive Adserver',
							'softname' => 'openx',
							'desc' => 'Revive Adserver is a Free Open Source Ad Server formerly known as OpenX Source.',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '3.0.5'
							),
				48 => array('name' => 'phpicalendar',
							'softname' => 'phpical',
							'desc' => 'phpicalendar is an open source php application to parse and display shared icalendar-compatible calendars on a website',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '2.31'
							),
				49 => array('name' => 'Booked',
							'softname' => 'phpsch',
							'desc' => 'Booked (formerly phpScheduleIt) is a simple but powerful reserve-anything scheduler.',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '2.5.8'
							),
				51 => array('name' => 'phpCollab',
							'softname' => 'phpcol',
							'desc' => 'phpCollab is an open source internet-enabled system for use in projects that require collaboration over the internet.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.5'
							),
				52 => array('name' => 'PHProjekt',
							'softname' => 'phproj',
							'desc' => 'PHProjekt is a modular application for the coordination of group activities and to share informations and document via the web',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '6.2.1'
							),
				54 => array('name' => 'ProjectPier',
							'softname' => 'pier',
							'desc' => 'ProjectPier is a Free, Open-Source, self-hosted PHP application for managing tasks, projects and teams through an intuitive web interface',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '0.8.8'
							),
				55 => array('name' => 'phpList',
							'softname' => 'phplist',
							'desc' => 'phplist is an open-source newsletter manager',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '3.0.10'
							),
				56 => array('name' => 'Webinsta Maillist',
							'softname' => 'mail',
							'desc' => 'WEBinsta mailing list manager is built to provide a centralized mailing list',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.3e'
							),
				57 => array('name' => 'poMMo',
							'softname' => 'pommo',
							'desc' => 'poMMo is versatile mass mailing software',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '16.1'
							),
				58 => array('name' => 'SquirrelMail',
							'softname' => 'squirrel',
							'desc' => 'SquirrelMail is a standards-based webmail package written in PHP',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.4.22'
							),
				59 => array('name' => 'ccMail',
							'softname' => 'ccmail',
							'desc' => 'CcMail is a free, open, powerful Mailing List Manager',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.0.2'
							),
				60 => array('name' => 'LimeSurvey',
							'softname' => 'lime',
							'desc' => 'The open source survey application',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.05+'
							),
				61 => array('name' => 'phpESP',
							'softname' => 'phpesp',
							'desc' => 'Create surveys, administer surveys, gather results, view statistics',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.1.4'
							),
				62 => array('name' => 'CJ Dynamic Poll',
							'softname' => 'cjdpoll',
							'desc' => 'It is a poll that changes dynamically',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.0'
							),
				63 => array('name' => 'EasyPoll',
							'softname' => 'easyp',
							'desc' => 'Easy Poll is a PHP script to create your own poll',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '1.0'
							),
				64 => array('name' => 'LittlePoll',
							'softname' => 'little',
							'desc' => 'The Amazing Little Poll is a very simple php polling script',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '1.3'
							),
				65 => array('name' => 'Simple PHP Poll',
							'softname' => 'phppoll',
							'desc' => 'Small and lightweight',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => 'v2'
							),
				66 => array('name' => 'Zen Cart',
							'softname' => 'zencart',
							'desc' => 'Putting the dream of online business ownership within reach of anyone!',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.5.3'
							),
				67 => array('name' => 'Magento',
							'softname' => 'magento',
							'desc' => 'Ecommerce platform for growth',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.9.0.1'
							),
				69 => array('name' => 'osCommerce',
							'softname' => 'oscom',
							'desc' => 'osCommerce is an online shop e-commerce solution',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2.3.4'
							),
				70 => array('name' => 'OpenCart 1.5',
							'softname' => 'ocart',
							'desc' => 'The Super Cool Ecommerce Solution',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.5.6.4'
							),
				72 => array('name' => 'PrestaShop',
							'softname' => 'presta',
							'desc' => 'PrestaShop is professional e-Commerce shopping cart software',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.6.0.9'
							),
				73 => array('name' => 'phpBook',
							'softname' => 'phpbook',
							'desc' => 'Allows you to add free guestbook to your site',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '2.1.0'
							),
				74 => array('name' => 'BellaBook',
							'softname' => 'bella',
							'desc' => 'BellaBook is a small and simple PHP guestbook',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '3.7'
							),
				75 => array('name' => 'VX Guestbook',
							'softname' => 'vxgb',
							'desc' => 'Allows you to add free guestbook to your site',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.07'
							),
				76 => array('name' => 'Lazarus',
							'softname' => 'lazarus',
							'desc' => 'Lazarus is a free guestbook script written in PHP',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.22'
							),
				77 => array('name' => 'RicarGBooK',
							'softname' => 'ricar',
							'desc' => 'RicarGBooK is a guestbook system written in PHP',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.2.2'
							),
				78 => array('name' => 'Advanced Guestbook',
							'softname' => 'agb',
							'desc' => 'Advanced Guestbook is a PHP-based guestbook script',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '2.4.4'
							),
				79 => array('name' => 'SMF',
							'softname' => 'smf',
							'desc' => 'SMF is a free, professional grade software package that allows you to set up your own online community',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '2.0.9'
							),
				80 => array('name' => 'Crafty Syntax',
							'softname' => 'crafty',
							'desc' => 'Crafty Syntax Live Help (CSLH) is an open source live support solution',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.4.7'
							),
				81 => array('name' => 'Help Center Live',
							'softname' => 'hcl',
							'desc' => 'Help Center Live is a Live Support tool written in PHP',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.1.7'
							),
				82 => array('name' => 'HESK',
							'softname' => 'hesk',
							'desc' => 'Hesk is Free PHP Help Desk Software that runs with a MySQL database',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.5.5'
							),
				83 => array('name' => 'osTicket',
							'softname' => 'ostic',
							'desc' => 'osTicket is a widely-used open source support ticket system',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.9.4'
							),
				84 => array('name' => 'ExoPHPDesk',
							'softname' => 'epdesk',
							'desc' => 'ExoPHPDesk is a free php helpdesk software',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.2.1'
							),
				86 => array('name' => 'Mibew Messenger',
							'softname' => 'owm',
							'desc' => 'Mibew Messenger is an open-source live support application written in PHP and MySQL',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.6.14'
							),
				87 => array('name' => 'phpOnline',
							'softname' => 'phpon',
							'desc' => 'phpOnline is a live customer support system',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.1.3'
							),
				88 => array('name' => 'Aardvark Topsites',
							'softname' => 'ats',
							'desc' => 'Aardvark Topsites PHP is a free topsites script built on PHP and MySQL',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '5.2.1'
							),
				92 => array('name' => 'Typo3 45',
							'softname' => 'typo',
							'desc' => 'TYPO3 is a free Open Source content management system for enterprise purposes',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '4.5.37'
							),
				95 => array('name' => 'phpLD',
							'softname' => 'phpld',
							'desc' => 'The most widely used directory script on the internet',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.2.0'
							),
				96 => array('name' => 'Pligg',
							'softname' => 'pligg',
							'desc' => 'Pligg is an open source Content Management System',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.0.2'
							),
				98 => array('name' => 'Moodle 2.6',
							'softname' => 'moodle',
							'desc' => 'Moodle is a Course Management System',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.6.5'
							),
				99 => array('name' => 'WeBid',
							'softname' => 'webid',
							'desc' => 'WeBid is an open-source auction script',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.1.1'
							),
				100 => array('name' => 'kPlaylist',
							'softname' => 'kplay',
							'desc' => 'kPlaylist is a free PHP system that makes your music collection available via the Internet',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '1.8.502'
							),
				101 => array('name' => 'Podcast Generator',
							'softname' => 'podcast',
							'desc' => 'Podcast Generator is a free web based podcast publishing script',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '2.3'
							),
				102 => array('name' => 'Impleo',
							'softname' => 'impleo',
							'desc' => 'Impleo is a simple PHP-script for managing your record collection',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '2.0'
							),
				104 => array('name' => 'BlackNova Traders',
							'softname' => 'bnt',
							'desc' => 'BlackNova Traders is a web-based, multi-player space exploration game inspired by the popular BBS game of TradeWars',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '0.663'
							),
				105 => array('name' => 'Shadows Rising',
							'softname' => 'sr',
							'desc' => 'Shadows Rising is a browser based RPG',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '0.0.5b'
							),
				106 => array('name' => 'Word Search Puzzle',
							'softname' => 'wsp',
							'desc' => 'Word Search Puzzle is a fun and simple game',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '1.0'
							),
				107 => array('name' => 'Multiplayer Checkers',
							'softname' => 'mc',
							'desc' => 'Play checkers and chat with this AJAX-enabled script',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '1.0.0'
							),
				108 => array('name' => 'PhpGedView',
							'softname' => 'gedview',
							'desc' => 'PhpGedView is a revolutionary genealogy program which allows you to view and edit your genealogy on your website',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '4.2.4'
							),
				109 => array('name' => 'MODX',
							'softname' => 'modx',
							'desc' => 'MODX helps you take control of your online content.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.3.2-pl'
							),
				110 => array('name' => 'eggBlog',
							'softname' => 'eggblog',
							'desc' => 'eggBlog is the free php & mysql blog software package',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '4.1.2'
							),
				111 => array('name' => 'phpAlbum',
							'softname' => 'album',
							'desc' => 'Create your personal Photo Album / Gallery in just seconds',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '0.4.1.16'
							),
				113 => array('name' => 'Claroline',
							'softname' => 'claro',
							'desc' => 'Claroline is an Open Source eLearning and eWorking platform',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '1.11.0'
							),
				114 => array('name' => 'PHPfileNavigator',
							'softname' => 'pfn',
							'desc' => 'PHPfileNavigator is state-of-the-art, open source web based application to complete manage your files and folders',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '2.3.3'
							),
				115 => array('name' => 'Mantis Bug Tracker',
							'softname' => 'mantis',
							'desc' => 'MantisBT is a free popular web-based bugtracking system',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '1.2.17'
							),
				116 => array('name' => 'Advanced Poll',
							'softname' => 'advpoll',
							'desc' => 'Advanced Poll is a polling system with powerful administration tool',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.0.9'
							),
				117 => array('name' => 'SugarCRM',
							'softname' => 'sugar',
							'desc' => 'Sugar CRM is the worlds leading provider of commercial open source customer relationship management (CRM) software.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '6.5.18'
							),
				118 => array('name' => 'Roundcube',
							'softname' => 'roundcube',
							'desc' => 'Roundcube - Free webmail for the masses.',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.0.3'
							),
				120 => array('name' => 'FluxBB',
							'softname' => 'fluxbb',
							'desc' => 'FluxBB is a free open source forum application designed to be fast, light and user friendly',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.5.7'
							),
				121 => array('name' => 'Dolphin',
							'softname' => 'dolph',
							'desc' => 'The worlds most advanced community software',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '7.1.4'
							),
				122 => array('name' => 'CubeCart',
							'softname' => 'cube',
							'desc' => 'CubeCart is a fully featured ecommerce shopping cart solution used by over a million store owners around the world',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '5.2.14'
							),
				123 => array('name' => 'CodeIgniter',
							'softname' => 'igniter',
							'desc' => 'CodeIgniter is a powerful PHP framework with a very small footprint',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.2.0'
							),
				127 => array('name' => 'phpFormGenerator',
							'softname' => 'form',
							'desc' => 'phpFormGenerator is a an easy, online tool for creating reliable, efficient, and aesthetically pleasing web forms in a snap',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.09'
							),
				129 => array('name' => 'phpMyFAQ',
							'softname' => 'myfaq',
							'desc' => 'phpMyFAQ is an open source FAQ system using PHP',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.8.15'
							),
				131 => array('name' => 'ClipBucket',
							'softname' => 'clip',
							'desc' => 'ClipBucket is free and opensource video sharing script , you can create your own youtube like website in matter of minutes!',
							'ins' => 1,
							'cat' => 'video',
							'type' => 'php',
							'ver' => '2.6'
							),
				133 => array('name' => '4images',
							'softname' => '4images',
							'desc' => '4images is as a web based PHP and MySQL for displaying images on the Internet',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '1.7.11'
							),
				136 => array('name' => 'OpenDocMan',
							'softname' => 'odm',
							'desc' => 'OpenDocMan is an opensource document management for the masses',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '1.2.9'
							),
				137 => array('name' => 'iQDesk',
							'softname' => 'iqdesk',
							'desc' => 'iQDesk is a unique software specifically designed for freelancers, small and any type of one-person-business',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.1'
							),
				138 => array('name' => 'Elgg',
							'softname' => 'elgg',
							'desc' => 'Elgg empowers individuals, groups and institutions to create their own fully-featured social environment',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '1.9.4'
							),
				140 => array('name' => 'Pixie',
							'softname' => 'pixie',
							'desc' => 'The Small, Simple, Site Maker',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '1.04'
							),
				144 => array('name' => 'WHMCS',
							'softname' => 'whmcs',
							'desc' => 'WHMCS is an all-in-one client management, billing & support solution for online businesses.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '5.3.10'
							),
				145 => array('name' => 'e107',
							'softname' => 'e107',
							'desc' => 'e107 is a content management system written in PHP and MySQL',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.0.4'
							),
				146 => array('name' => 'OpenClassifieds',
							'softname' => 'openclass',
							'desc' => 'OpenClassifieds is a free open source script for classifieds, advertisement or listings',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '2.2.1'
							),
				153 => array('name' => 'script.aculo.us',
							'softname' => 'scriptaculous',
							'desc' => 'script.aculo.us provides you with easy-to-use, cross-browser user interface JavaScript libraries to make your web sites and web applications fly',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.9.0'
							),
				154 => array('name' => 'jQuery',
							'softname' => 'jquery',
							'desc' => 'jQuery is a new kind of JavaScript Library',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.11.1'
							),
				155 => array('name' => 'Ext JS',
							'softname' => 'extjs',
							'desc' => 'Ext JS is a JavaScript platform for rapid development of cross-browser web apps',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '4.2.1'
							),
				156 => array('name' => 'Scripty2',
							'softname' => 'scripty2',
							'desc' => 'scripty2 is a powerful, flexible JavaScript framework',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.0.0 B1'
							),
				157 => array('name' => 'MochiKit',
							'softname' => 'mochikit',
							'desc' => 'A lightweight Javascript library',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.4.2'
							),
				158 => array('name' => 'MooTools',
							'softname' => 'mootools',
							'desc' => 'MooTools is a compact, modular, Object-Oriented JavaScript framework designed for the intermediate to advanced JavaScript developer',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.5.1'
							),
				159 => array('name' => 'YUI',
							'softname' => 'yui',
							'desc' => 'YUI 3 is Yahoos next-generation JavaScript and CSS library',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '3.18.1'
							),
				160 => array('name' => 'Prototype',
							'softname' => 'prototype',
							'desc' => 'Prototype is a JavaScript Framework that aims to ease development of dynamic web applications',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.7.2'
							),
				161 => array('name' => 'Rico',
							'softname' => 'rico',
							'desc' => 'Javascript for rich internet applications',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.1'
							),
				162 => array('name' => 'Dojo',
							'softname' => 'dojo',
							'desc' => 'Ajax, events, packaging, CSS-based querying, animations, JSON, language utilities, and a lot more',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.10.2'
							),
				163 => array('name' => 'AJS',
							'softname' => 'ajs',
							'desc' => 'The ultra lightweight JavaScript library',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '4.6'
							),
				164 => array('name' => 'Raphael',
							'softname' => 'raphael',
							'desc' => 'Raphael is a small JavaScript library that should simplify your work with vector graphics on the web',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.1.2'
							),
				165 => array('name' => 'Sizzle',
							'softname' => 'sizzle',
							'desc' => 'A pure-JavaScript CSS selector engine
designed to be easily dropped in to a host library',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.0.0'
							),
				170 => array('name' => 'VidiScript',
							'softname' => 'vidi',
							'desc' => 'VidiScript is an open source video sharing community script',
							'ins' => 1,
							'cat' => 'video',
							'type' => 'php',
							'ver' => '1.0.3a'
							),
				171 => array('name' => 'Piwik',
							'softname' => 'piwik',
							'desc' => 'Piwik is a open source web analytics software program',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.8.3'
							),
				172 => array('name' => 'YOURLS',
							'softname' => 'yourls',
							'desc' => 'YOURLS is a small set of PHP scripts that will allow you to run your own URL shortening service',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.7'
							),
				173 => array('name' => 'Gregarius',
							'softname' => 'greg',
							'desc' => 'Gregarius is a web-based RSS/RDF/ATOM feed aggregator',
							'ins' => 1,
							'cat' => 'rss',
							'type' => 'php',
							'ver' => '0.6.1'
							),
				174 => array('name' => 'Concrete5',
							'softname' => 'conc',
							'desc' => 'Concrete5 makes running a website easy.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '5.7.2'
							),
				175 => array('name' => 'phpwcms',
							'softname' => 'phpwcms',
							'desc' => 'phpwcms is a robust and simple but yet powerful web based content management system',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.7.5'
							),
				176 => array('name' => 'WikkaWiki',
							'softname' => 'wikka',
							'desc' => 'Wikkawiki is a flexible, standards-compliant and lightweight wiki engine.',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '1.3.5'
							),
				177 => array('name' => 'bbPress',
							'softname' => 'bbpress',
							'desc' => 'bbPress is forum software with a twist from the creators of WordPress.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.2'
							),
				181 => array('name' => 'phpFreeChat',
							'softname' => 'phpchat',
							'desc' => 'phpFreeChat is a free chat system',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.7'
							),
				182 => array('name' => 'Jcow',
							'softname' => 'jcow',
							'desc' => 'Jcow is a flexible Social Networking software written in PHP. ',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '9.2'
							),
				183 => array('name' => 'StatusNet',
							'softname' => 'status',
							'desc' => 'StatusNet is the open source microblogging platform',
							'ins' => 1,
							'cat' => 'microblogs',
							'type' => 'php',
							'ver' => '1.1.1'
							),
				188 => array('name' => 'Feng Office',
							'softname' => 'feng',
							'desc' => 'Feng Office is a Collaboration Platform that enables you to manage your projects and business services',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.7.1.6'
							),
				191 => array('name' => 'eyeOS',
							'softname' => 'eyeos',
							'desc' => 'eyeOS  is a disruptive desktop entirely usable from a web browser.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.5'
							),
				192 => array('name' => 'OrangeHRM',
							'softname' => 'orange',
							'desc' => 'OrangeHRM aims to be the worlds leading open source HRM solution for small and medium sized enterprises',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '3.2.1'
							),
				195 => array('name' => 'ProjectSend',
							'softname' => 'cftp',
							'desc' => 'ProjectSend is a file sharing utility',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => 'r561'
							),
				199 => array('name' => 'PHP QR Code',
							'softname' => 'phpqrcode',
							'desc' => 'PHP QR Code is an open source library for generating QR Code, 2-dimensional barcode',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.1.4'
							),
				201 => array('name' => 'FrontAccounting',
							'softname' => 'front',
							'desc' => 'FrontAccounting is an accounting system for small companies.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '2.3.22'
							),
				202 => array('name' => 'Dolibarr',
							'softname' => 'dolibarr',
							'desc' => 'Dolibarr is a software built by modules addition, to manage small or medium companies, freelancers or foundations.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '3.6.1'
							),
				210 => array('name' => 'ATutor',
							'softname' => 'atutor',
							'desc' => 'ATutor is an Open Source Web-based Learning Management System (LMS)',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.1.1'
							),
				214 => array('name' => 'Vanilla',
							'softname' => 'vanilla',
							'desc' => 'Vanilla Forums are open-source, standards-compliant, customizable discussion forums.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '2.1.3'
							),
				219 => array('name' => 'PHPDevShell',
							'softname' => 'phpdevshell',
							'desc' => 'PHPDevShell  is a Highly modular plugin based Code Management System and Framework',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '3.2.0'
							),
				221 => array('name' => 'PRADO',
							'softname' => 'prado',
							'desc' => 'PRADO stands for PHP Rapid Application Development Object-oriented.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '3.2.4'
							),
				224 => array('name' => 'yii',
							'softname' => 'yii',
							'desc' => 'YiiFramework helps Web developers build complex applications and deliver them on-time',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '1.1.15'
							),
				225 => array('name' => 'Zend',
							'softname' => 'zend',
							'desc' => 'Zend Framework is based on simplicity, object-oriented best practices',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.3.3'
							),
				227 => array('name' => 'Vtiger',
							'softname' => 'vtiger',
							'desc' => 'Vtiger CRM is a free CRM software ideal for small and medium businesses, with low-cost product support available to production users that need reliable support.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '6.1.0'
							),
				231 => array('name' => 'The Bug Genie',
							'softname' => 'buggenie',
							'desc' => 'The Bug Genie is a bug tracking tool',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '3.2.7.1'
							),
				234 => array('name' => 'TaskFreak',
							'softname' => 'taskfreak',
							'desc' => 'TaskFreak! Original is a simple web based task manager',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '0.6.4'
							),
				236 => array('name' => 'TCExam',
							'softname' => 'tcexam',
							'desc' => 'TCExam is a FLOSS system for electronic exams',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '12.1.024'
							),
				238 => array('name' => 'LetoDMS',
							'softname' => 'leto',
							'desc' => 'LetoDMS is an open-source document-management-system based on PHP and MySQL.',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '3.4.2'
							),
				239 => array('name' => 'DoceboLMS',
							'softname' => 'docebo',
							'desc' => 'DoceboLMS is a SCORM compliant Open Source e-Learning platform used in corporate, government and education markets.',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '4.0.5'
							),
				242 => array('name' => 'DIY',
							'softname' => 'diy',
							'desc' => 'DIY is an open-source lightweight web application framework',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '0.3'
							),
				243 => array('name' => 'OpenBiz Cubi',
							'softname' => 'openbiz',
							'desc' => 'OpenBiz Cubi Platform is a fast application development platform designed for business applications.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '3.0.9'
							),
				247 => array('name' => 'CMS Made Simple',
							'softname' => 'cmssimple',
							'desc' => 'CMS Made Simple provides a fast and easy way to create a professional web site',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.11.11'
							),
				248 => array('name' => 'PaintbrushJS',
							'softname' => 'paintbrushjs',
							'desc' => 'PaintbrushJS is a lightweight browser-based image processing library ',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '0.3'
							),
				249 => array('name' => 'OpenNewsletter',
							'softname' => 'newsletter',
							'desc' => 'OpenNewsletter is a web-based newsletter system',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '2.5.1'
							),
				250 => array('name' => 'TheHostingTool',
							'softname' => 'tht',
							'desc' => 'TheHostingTool is a free hosting billing software',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.2.6'
							),
				252 => array('name' => 'TomatoCart',
							'softname' => 'tomatocart',
							'desc' => 'TomatoCart is open source shopping cart software using the ExtJS RIA framework',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.1.8.6.1'
							),
				253 => array('name' => 'Kohana',
							'softname' => 'kohana',
							'desc' => 'Kohana is an elegant HMVC PHP5 framework ',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '3.3.2'
							),
				258 => array('name' => 'Oxwall',
							'softname' => 'oxwall',
							'desc' => 'Oxwall is unbelievably flexible and easy to use PHP/MySQL community software platform.',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '1.7.1'
							),
				259 => array('name' => 'SimplePie',
							'softname' => 'pie',
							'desc' => 'SimplePie is a very fast and easy-to-use class, written in PHP, that puts the simple back into really simple syndication. ',
							'ins' => 1,
							'cat' => 'rss',
							'type' => 'php',
							'ver' => '1.3.1'
							),
				260 => array('name' => 'SimpleInvoices',
							'softname' => 'invoices',
							'desc' => 'Simple Invoices focuses on the basic needs of invoicing yet gives users advanced flexibility without compromising simplicity.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2011.1'
							),
				261 => array('name' => 'ExtCalendar',
							'softname' => 'extcal',
							'desc' => 'ExtCalendar is a calendar application, with an integrated event managemt system.',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '2.0'
							),
				262 => array('name' => 'Beatz',
							'softname' => 'beatz',
							'desc' => 'Beatz is an online social networking community script that allows you to start your own favourite artist band website.',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '1.1'
							),
				263 => array('name' => 'Form Tools',
							'softname' => 'ftools',
							'desc' => 'Form Tools is a PHP / MySQL script that manages the form submission data.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.2.6'
							),
				264 => array('name' => 'Etano',
							'softname' => 'etano',
							'desc' => 'Etano can be used to start up a dating site, a social networking site, a classifieds site.',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '1.23'
							),
				267 => array('name' => 'Contao',
							'softname' => 'contao',
							'desc' => 'Contao is an open source content management system (CMS) for people who want a professional internet presence that is easy to maintain.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.3.5'
							),
				268 => array('name' => 'Plogger',
							'softname' => 'plogger',
							'desc' => 'Plogger is the next generation in open-source photo gallery systems.',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '1.0'
							),
				269 => array('name' => 'Trellis Desk',
							'softname' => 'trellis',
							'desc' => 'Trellis Desk is a powerful and robust help desk solution for your business.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.0.4'
							),
				270 => array('name' => 'phpDocumentor',
							'softname' => 'documentor',
							'desc' => 'phpDocumentor tool is a standalone auto-documentor similar to JavaDoc written in PHP.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.4.4'
							),
				272 => array('name' => 'AmpJuke',
							'softname' => 'ampjuke',
							'desc' => 'AmpJuke will act as your streaming server.',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '0.8.8'
							),
				273 => array('name' => 'FUDforum',
							'softname' => 'fud',
							'desc' => 'FUDforum (Fast Uncompromising Discussion Forum) is a free and open source web discussion forum released under the GPL (version 2) license that is written in PHP and can be used on virtually any operating system.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '3.0.5'
							),
				275 => array('name' => 'PHPKode Guestbook',
							'softname' => 'phpkode',
							'desc' => 'PHPKode Guestbook is a simple yet powerful Free PHP guestbook script using Ajax.',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.0'
							),
				276 => array('name' => 'Omeka',
							'softname' => 'omeka',
							'desc' => 'Omeka is a free, flexible, and open source web-publishing platform for the display of library, museum, archives, and scholarly collections and exhibitions.',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.2.2'
							),
				279 => array('name' => 'phpMyAdmin',
							'softname' => 'myadmin',
							'desc' => 'phpMyAdmin is a free software tool written in PHP intended to handle the administration of MySQL over the World Wide Web.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '4.2.10.1'
							),
				280 => array('name' => 'Adminer',
							'softname' => 'adminer',
							'desc' => 'Adminer is a full-featured database management tool written in PHP.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '4.1.0'
							),
				282 => array('name' => 'SQLiteManager',
							'softname' => 'sqlite',
							'desc' => 'SQLiteManager is a database manager for SQLite databases. You can manage any SQLite database created on any platform with SQLiteManager.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '1.2.4'
							),
				283 => array('name' => 'Hablator',
							'softname' => 'hablator',
							'desc' => 'The Hablator is an advanced GPLed chat script written in PHP and Javascript.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '0.5.2'
							),
				284 => array('name' => 'Traq',
							'softname' => 'traq',
							'desc' => 'Traq is a PHP and MySQL powered Project Tracker, you can easily track Milestones, Versions, Bugs, Feature Requests and see how far your project has come.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '3.5.2'
							),
				287 => array('name' => 'SilverStripe',
							'softname' => 'stripe',
							'desc' => 'SilverStripe CMS is an open source web content management system used by governments, businesses, and non-profit organisations around the world.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.1.6'
							),
				289 => array('name' => 'PyroCMS',
							'softname' => 'pyro',
							'desc' => 'PyroCMS is an open source, object oriented content management system built using PHP5 and CodeIgniter.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.2.5'
							),
				290 => array('name' => 'PageCookery',
							'softname' => 'page',
							'desc' => 'PageCookery is the first public offering of single-user version of the open source microblogging program.',
							'ins' => 1,
							'cat' => 'microblogs',
							'type' => 'php',
							'ver' => '0.9.9'
							),
				293 => array('name' => 'Redaxscript',
							'softname' => 'redax',
							'desc' => 'Redaxscript is a free, PHP and MySQL driven content management system for small business and private websites. Its extremely lightweight, simple and customizable.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.1.0'
							),
				294 => array('name' => 'GPixPixel',
							'softname' => 'gpix',
							'desc' => 'GPixPixel is a FREE yet powerful million pixel script, based on the popular marketing concept.',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '1.4.1'
							),
				295 => array('name' => 'Arfooo',
							'softname' => 'arfooo',
							'desc' => 'Arfooo is the most powerful free and open source directory script in the world.',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '2.0.2'
							),
				296 => array('name' => 'PHPWeby',
							'softname' => 'weby',
							'desc' => 'PHP Weby directory is a powerful and easy-to-use FREE link management script with numerous options for running a directory, catalog of sites or a simple link exchange system.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.2'
							),
				299 => array('name' => 'Avactis',
							'softname' => 'avactis',
							'desc' => 'Avactis offers an extremely convenient set of tools to quickly launch an online business.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '4.6'
							),
				300 => array('name' => 'Smarty',
							'softname' => 'smarty',
							'desc' => 'Smarty is a template engine for PHP, facilitating the separation of presentation (HTML/CSS) from application logic.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '3.1.21'
							),
				302 => array('name' => 'videoDB',
							'softname' => 'videodb',
							'desc' => 'VideoDB is a web application to manage a personal video collection.',
							'ins' => 1,
							'cat' => 'video',
							'type' => 'php',
							'ver' => '4.0.0'
							),
				303 => array('name' => 'Collabtive',
							'softname' => 'collab',
							'desc' => 'Collabtive is web-based project management software.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.0'
							),
				304 => array('name' => 'PASTE',
							'softname' => 'paste',
							'desc' => 'PASTE is an open source pastebin forked from the original pastebin.com script.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.9'
							),
				306 => array('name' => 'PivotX',
							'softname' => 'pivotx',
							'desc' => 'PivotX is free software to help you maintain dynamic sites such as weblogs, online journals and other frequently updated websites in general.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '2.3.10'
							),
				307 => array('name' => 'phpCOIN',
							'softname' => 'coin',
							'desc' => 'phpCOIN a free WebWare package originally designed for web-hosting resellers.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.6.5'
							),
				308 => array('name' => 'PHP-Fusion',
							'softname' => 'fusion',
							'desc' => 'PHP-Fusion is a light-weight open-source content management system (CMS) written in PHP 5.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '7.02.07'
							),
				312 => array('name' => 'Chamilo',
							'softname' => 'chamilo',
							'desc' => 'Chamilo is a fully-fledged e-learning system.',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '1.9.8'
							),
				313 => array('name' => 'Dokeos',
							'softname' => 'dokeos',
							'desc' => 'Dokeos is an elearning and course management web application.',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.1.1'
							),
				314 => array('name' => 'Open Journal Systems',
							'softname' => 'ojs',
							'desc' => 'Open Journal Systems (OJS) is a journal management and publishing system.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.4.5.0'
							),
				319 => array('name' => 'Quick.Cart',
							'softname' => 'qcart',
							'desc' => 'Simple and functional shopping cart for you and your customers.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '6.5'
							),
				320 => array('name' => 'Tine 2.0',
							'softname' => 'tine',
							'desc' => 'Tine 2.0 is an open source project which combines groupware and CRM in one consistent interface.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '2014.09.2'
							),
				321 => array('name' => 'Axis',
							'softname' => 'axis',
							'desc' => 'Axis commerce is a powerfull open source e-commerce platform.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '0.8.7.2'
							),
				322 => array('name' => 'Feed On Feeds',
							'softname' => 'feed',
							'desc' => 'Feed On Feeds is a server side, multi-user RSS and Atom aggregator!',
							'ins' => 1,
							'cat' => 'rss',
							'type' => 'php',
							'ver' => '0.5'
							),
				323 => array('name' => 'EGroupware',
							'softname' => 'egroup',
							'desc' => 'EGroupware is the leading Online Collaboration Tool.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '14.1'
							),
				324 => array('name' => 'Movable Type',
							'softname' => 'mt',
							'desc' => 'Powerful enough for building websites, blogs, and communities on a single platform.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'perl',
							'ver' => '5.2.10'
							),
				325 => array('name' => 'OpenBiblio',
							'softname' => 'biblio',
							'desc' => 'OpenBiblio is an easy to use, automated library system written in PHP containing OPAC, circulation, cataloging, and staff administration functionality.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '0.7.2'
							),
				326 => array('name' => 'Seo Panel',
							'softname' => 'seo',
							'desc' => 'Seo Panel is a complete open source seo control panel for managing search engine optimization of your websites.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '3.6.0'
							),
				327 => array('name' => 'Vty',
							'softname' => 'vty',
							'desc' => 'Vty is a web-based database manager script written with Php. It\'s for Mysql.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '1.6'
							),
				328 => array('name' => 'Soholaunch',
							'softname' => 'soho',
							'desc' => 'Soholaunch is an easy-to-use website builder designed to help you build, maintain, and manage your personal or business website.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => 'v4.9.4 r25'
							),
				330 => array('name' => 'OSClass',
							'softname' => 'osclass',
							'desc' => 'It is a free and open script to create your advertisement or listings site.',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '3.4.3'
							),
				331 => array('name' => 'jobberBase',
							'softname' => 'jobber',
							'desc' => 'jobberBase is the open-source job board software that helps you set up a jobsite in minutes!',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.9.1'
							),
				332 => array('name' => 'Question2Answer',
							'softname' => 'qtoa',
							'desc' => 'Question2Answer site helps your online community to share knowledge. People with questions quickly get the answers they need.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.6.3'
							),
				333 => array('name' => 'JoobsBox',
							'softname' => 'joobs',
							'desc' => 'JoobsBox is the most flexible software for job boards, with a plugins and themes system ready for your needs.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '0.9.20090730'
							),
				334 => array('name' => 'Zeuscart',
							'softname' => 'zeus',
							'desc' => 'Zeuscart is an incredibly stable & richly-interfaced, open source shopping cart.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '4.0'
							),
				335 => array('name' => 'Silex',
							'softname' => 'silex',
							'desc' => 'Silex is a free and open source software that allows to create Flash and Html websites directly in the browser without writing code.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => 'v1.7.0'
							),
				336 => array('name' => 'Saurus',
							'softname' => 'saurus',
							'desc' => 'Saurus is Free, Open Source Software for Building and Managing Websites.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '4.7.FINAL'
							),
				337 => array('name' => 'eFront',
							'softname' => 'efront',
							'desc' => 'eFront Enterprise is an effective learning system that can make your HR department a little happier. ',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '3.6.14'
							),
				338 => array('name' => 'Pydio',
							'softname' => 'pydio',
							'desc' => 'Pydio: Put Your Data In Orbit!',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '5.2.5'
							),
				339 => array('name' => 'jCore',
							'softname' => 'jcore',
							'desc' => 'jCore is a free and open source content management system (CMS) written in PHP.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '0.9'
							),
				340 => array('name' => 'Sharetronix',
							'softname' => 'share',
							'desc' => 'Sharetronix is the world\'s favorite opensource microblogging platform.',
							'ins' => 1,
							'cat' => 'microblogs',
							'type' => 'php',
							'ver' => '3.6.0'
							),
				341 => array('name' => 'MyWebSQL',
							'softname' => 'myweb',
							'desc' => 'Manage your MySQL databases over the web using a secure and intuitive interface with blazing fast performance.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '3.6'
							),
				342 => array('name' => 'PeoplePods',
							'softname' => 'pods',
							'desc' => 'PeoplePods is a developer-friendly social software toolkit.',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '0.9'
							),
				343 => array('name' => 'Moodle 2.0',
							'softname' => 'moodle20',
							'desc' => 'Moodle is a Course Management System',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.0.10'
							),
				344 => array('name' => 'AlegroCart',
							'softname' => 'alegro',
							'desc' => 'Alegro Cart is a free open source e-commerce shopping cart solution based on MVC Framework.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.2.8'
							),
				345 => array('name' => 'Symfony2',
							'softname' => 'symfony2',
							'desc' => 'Symfony is aimed at building robust applications in an enterprise context.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.3.21'
							),
				346 => array('name' => 'jqPlot',
							'softname' => 'jqplot',
							'desc' => 'jqplot is a plotting and charting plugin for the jQuery Javascript framework.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '0.9.7'
							),
				347 => array('name' => 'PHPlot',
							'softname' => 'phplot',
							'desc' => 'PHPlot is a graph library for dynamic scientific, business, and stock-market charts.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '6.1.0'
							),
				348 => array('name' => 'JSZip',
							'softname' => 'jszip',
							'desc' => 'JSZip creates .zip files with Javascript.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.4.0'
							),
				349 => array('name' => 'Elycharts',
							'softname' => 'ely',
							'desc' => 'ElyCharts is a pure javascript charting library, easy to use and completely customizable.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.1.5'
							),
				350 => array('name' => 'jsMorph',
							'softname' => 'morph',
							'desc' => 'jsMorph is a morphing - motion - tweening framework that knows what you need to do.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '0.5.0'
							),
				352 => array('name' => 'php.JS',
							'softname' => 'phpjs',
							'desc' => 'php.JS helps to use PHP functions in JavaScript.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '3.26'
							),
				353 => array('name' => 'Modernizr',
							'softname' => 'modernizr',
							'desc' => 'Modernizr is a small JavaScript library that detects the availability of native implementations for next-generation web technologies',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.8.3'
							),
				354 => array('name' => 'Fork',
							'softname' => 'fork',
							'desc' => 'Fork is an open source CMS that will rock your world.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.8.2'
							),
				357 => array('name' => 'Storytlr',
							'softname' => 'story',
							'desc' => 'Storyltr offers a single touch point for your online life in your own style.',
							'ins' => 1,
							'cat' => 'microblogs',
							'type' => 'php',
							'ver' => '1.2.0'
							),
				359 => array('name' => 'Chyrp',
							'softname' => 'chyrp',
							'desc' => 'Chyrp is a blogging engine designed to be very lightweight while retaining functionality.',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '2.5'
							),
				360 => array('name' => 'WideImage',
							'softname' => 'wide',
							'desc' => 'WideImage is an object-oriented library for image manipulation.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '11.02.19'
							),
				361 => array('name' => 'HTML Purifier',
							'softname' => 'purifier',
							'desc' => 'HTML Purifier is a standards-compliant HTML filter library written in PHP.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '4.6.0'
							),
				362 => array('name' => 'selfoss',
							'softname' => 'selfoss',
							'desc' => 'selfoss is a multipurpose rss reader, live stream, mashup, aggregation web application.',
							'ins' => 1,
							'cat' => 'rss',
							'type' => 'php',
							'ver' => '2.12'
							),
				367 => array('name' => 'Mahara',
							'softname' => 'mahara',
							'desc' => 'Mahara is an open source e-portfolio system with a flexible display framework.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.9.3'
							),
				368 => array('name' => 'ownCloud',
							'softname' => 'owncloud',
							'desc' => 'ownCloud gives you universal access to your files through a web interface or WebDAV.',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '7.0.2'
							),
				370 => array('name' => 'miniBB',
							'softname' => 'minibb',
							'desc' => 'miniBB is a standalone, open source program for building your own Internet forum.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '3.1'
							),
				371 => array('name' => 'ArticleSetup',
							'softname' => 'article',
							'desc' => 'ArticleSetup is the powerful, flexible, and surprisingly simple web software that you can use to setup your own article directory website.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.00'
							),
				373 => array('name' => 'Open Web Analytics',
							'softname' => 'owa',
							'desc' => 'Open Web Analytics is a software that you can use to track and analyze how people use your web sites and applications.',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '1.5.7'
							),
				375 => array('name' => 'GLPI',
							'softname' => 'glpi',
							'desc' => 'GLPI is the Information Resource-Manager with an additional Administration- Interface.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '0.84.8'
							),
				376 => array('name' => 'WebMail Lite',
							'softname' => 'webmail',
							'desc' => 'WebMail Lite is Fast and easy-to-use webmail front-end for your existing IMAP mail server.',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '7.4.1'
							),
				377 => array('name' => 'CakePHP',
							'softname' => 'cake',
							'desc' => 'CakePHP makes building web applications simpler, faster and require less code.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.5.5'
							),
				379 => array('name' => 'Tribiq',
							'softname' => 'tribiq',
							'desc' => 'Tribiq CMS is a browser-based, multilingual content management system.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '6.0.5a'
							),
				380 => array('name' => 'SVNManager',
							'softname' => 'svnman',
							'desc' => 'SVNManager is a PHP web based tool to administer a Apache Subversion repository server.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.09'
							),
				381 => array('name' => 'ImpressCMS',
							'softname' => 'impress',
							'desc' => 'ImpressCMS is a community developed Content Management System for easily building and maintaining a dynamic web site.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.3.7'
							),
				382 => array('name' => 'Typo3',
							'softname' => 'typo47',
							'desc' => 'TYPO3 is a free Open Source content management system for enterprise purposes',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '6.2.6'
							),
				383 => array('name' => 'Gallery 2',
							'softname' => 'gallery2',
							'desc' => 'Gallery is an open source web based photo album organizer',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '2.3.2'
							),
				384 => array('name' => 'SPIP',
							'softname' => 'spip',
							'desc' => 'SPIP is a publishing system for the Internet.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '3.0.17'
							),
				386 => array('name' => 'Quick.CMS',
							'softname' => 'qcms',
							'desc' => 'Easy to customize and use content management system. CMS gives possiblity to add unique design to every page.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '5.5'
							),
				387 => array('name' => 'BoxBilling',
							'softname' => 'boxbill',
							'desc' => 'Complete client management, billing & support software. BoxBilling is free and will always be free!',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '3.6.11'
							),
				388 => array('name' => 'Open Conference Systems',
							'softname' => 'ocs',
							'desc' => 'Open Conference Systems (OCS) is a free Web publishing tool that will create a complete Web presence for your scholarly conference.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.3.6.0'
							),
				389 => array('name' => 'AbanteCart',
							'softname' => 'abante',
							'desc' => 'AbanteCart is a free PHP based eCommerce solution for merchants to provide ability creating online business and sell products online quick and efficient.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.1.9'
							),
				390 => array('name' => 'ImpressPages',
							'softname' => 'impresspage',
							'desc' => 'ImpressPages is user friendly software. Its tools enable user to manage the content of website in a convenient way.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '4.2.6'
							),
				391 => array('name' => 'Pluck',
							'softname' => 'pluck',
							'desc' => 'Pluck is your small and simple content management system, written in php. With pluck, you can easily manage your own website without knowledge of programming languages.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '4.7.2'
							),
				392 => array('name' => 'Maian Support',
							'softname' => 'maian',
							'desc' => 'Maian Support is a FREE support ticket system written in PHP/MySQL.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.0'
							),
				393 => array('name' => 'Logaholic',
							'softname' => 'logaholic',
							'desc' => 'Logaholic is is designed to give you the easiest, quickest, most intuitive view of any set of information.',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '4.2.3'
							),
				394 => array('name' => 'Eventum',
							'softname' => 'eventum',
							'desc' => 'Eventum is a user-friendly and flexible issue tracking system.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.2'
							),
				397 => array('name' => 'SIDU',
							'softname' => 'sidu',
							'desc' => 'SIDU is a FREE database client working via web browser. SIDU stands for SQL Select Insert Delete Update.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '5.1'
							),
				398 => array('name' => 'Chive',
							'softname' => 'chive',
							'desc' => 'Chive is a modern Open-Source MySQL Data Management tool. With it\'s fast and elaborate user interface it is getting very popular especially by web engineers.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '1.3.1'
							),
				399 => array('name' => 'razorCMS',
							'softname' => 'razor',
							'desc' => 'razorCMS is File Based Content Management System (FBCMS)',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.3.11'
							),
				400 => array('name' => 'BIGACE',
							'softname' => 'bigace',
							'desc' => 'BIGACE is a free and professional grade software package that allows you to set up your own website within minutes.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.7.8'
							),
				401 => array('name' => 'eSyndiCat',
							'softname' => 'esyndicat',
							'desc' => 'eSyndiCat is a professional, affordable php directory software.',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '1.7'
							),
				403 => array('name' => 'RockMongo',
							'softname' => 'mongo',
							'desc' => 'RockMongo, a MongoDB administration tool, written in PHP5, is Best in PHP world, more like PHPMyAdmin.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '1.1.7'
							),
				406 => array('name' => 'eXtplorer',
							'softname' => 'extplorer',
							'desc' => 'eXtplorer is a php-based file manager for your own web space. It\'s cross-browser compliant and offers everything you need.',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '2.1.5'
							),
				407 => array('name' => 'EPESI',
							'softname' => 'epesi',
							'desc' => 'EPESI is a web application for managing business information.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '1.6.2'
							),
				408 => array('name' => 'Subrion',
							'softname' => 'subrion',
							'desc' => 'Subrion CMS is a stand-alone PHP content management system that is very easy to use.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.2.0'
							),
				409 => array('name' => 'Support Incident Tracker',
							'softname' => 'sit',
							'desc' => 'Support Incident Tracker (or SiT!) is a Free Software/Open Source (GPL) web based application which uses PHP and MySQL for tracking technical support calls/emails.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.66'
							),
				410 => array('name' => 'ShopSite',
							'softname' => 'shopsite',
							'desc' => 'ShopSite is the easiest-to-use shopping cart software for small to medium-sized businesses.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'perl',
							'ver' => '11.2.3'
							),
				411 => array('name' => 'Nibbleblog',
							'softname' => 'nibble',
							'desc' => 'Nibbleblog Easy, fast and free CMS Blog',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '4.0.3'
							),
				413 => array('name' => 'Joomla',
							'softname' => 'joomla30',
							'desc' => 'Joomla is an award-winning CMS, which enables you to build Web sites and powerful online applications.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.3.6'
							),
				414 => array('name' => 'Codiad',
							'softname' => 'codiad',
							'desc' => 'Codiad is a web-based IDE framework with a small footprint and minimal requirements.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.4.0'
							),
				415 => array('name' => 'Flyspray',
							'softname' => 'flyspray',
							'desc' => 'Flyspray is an uncomplicated, web-based bug tracking system written in PHP for assisting with software development.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '0.9.9.7'
							),
				416 => array('name' => 'todoyu',
							'softname' => 'todoyu',
							'desc' => 'todoyu is the web-based way to get your tasks done. todoyu is all about bringing your team and clients together to work jointly on projects.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.3.1'
							),
				417 => array('name' => 'PrestaShop 1.4',
							'softname' => 'presta14',
							'desc' => 'PrestaShop is professional e-Commerce shopping cart software.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.4.11.0'
							),
				419 => array('name' => 'Laravel',
							'softname' => 'laravel',
							'desc' => 'Laravel is a PHP framework committed to elegance and simplicity.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '4.2.11'
							),
				420 => array('name' => 'Pimcore',
							'softname' => 'pimcore',
							'desc' => 'Pimcore is an open source CMS that will rock your world.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.3.0'
							),
				421 => array('name' => 'MediaWiki 1.19',
							'softname' => 'mw19',
							'desc' => 'MediaWiki is a free software wiki package written in PHP, originally for use on Wikipedia.',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '1.19.21'
							),
				425 => array('name' => 'Flot',
							'softname' => 'flot',
							'desc' => 'Attractive JavaScript plotting for jQuery.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '0.8.3'
							),
				426 => array('name' => 'Bootstrap',
							'softname' => 'bootstrap',
							'desc' => 'Bootstrap Sleek, intuitive, and powerful front-end framework for faster and easier web development.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '3.3.0'
							),
				427 => array('name' => 'LESS',
							'softname' => 'less',
							'desc' => 'LESS extends CSS with dynamic behavior such as variables, mixins, operations and functions.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.7.5'
							),
				428 => array('name' => 'qdPM',
							'softname' => 'qdpm',
							'desc' => 'qdPM is a free web-based project management tool suitable for a small team working on multiple projects.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '8.3'
							),
				430 => array('name' => 'Monstra',
							'softname' => 'monstra',
							'desc' => 'Monstra is a fast and small content management system written in PHP!',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '3.0.1'
							),
				431 => array('name' => 'phpLiteAdmin',
							'softname' => 'phplite',
							'desc' => 'phpLiteAdmin is a web-based SQLite database admin tool written in PHP with support for SQLite2 and SQLite3.',
							'ins' => 1,
							'cat' => 'dbtools',
							'type' => 'php',
							'ver' => '1.9.5'
							),
				432 => array('name' => 'FuelPHP',
							'softname' => 'fuel',
							'desc' => 'FuelPHP is a simple, flexible, community driven PHP 5.3+ framework, based on the best ideas of other frameworks, with a fresh start!',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '1.7.2'
							),
				433 => array('name' => 'Tiki Wiki CMS Groupware',
							'softname' => 'tiki10',
							'desc' => 'TikiWiki (Tiki) is your Groupware/CMS (Content Management System) solution',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '12.2'
							),
				434 => array('name' => 'Vision Helpdesk',
							'softname' => 'vision',
							'desc' => 'Vision Helpdesk is a Web-Based True Satellite Helpdesk Software that allows you to manage support for Multiple Companies at one place.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.9.10'
							),
				435 => array('name' => 'Prismotube Express',
							'softname' => 'prismo',
							'desc' => 'Prismotube is a PHP Video Script that auto creates thousands of video pages based on your targeted keywords.',
							'ins' => 1,
							'cat' => 'video',
							'type' => 'php',
							'ver' => '1.13'
							),
				436 => array('name' => 'Zurmo',
							'softname' => 'zurmo',
							'desc' => 'Zurmo is an Open Source Customer Relationship Management (CRM) application that is mobile, social, and gamified.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '2.8.3'
							),
				437 => array('name' => 'CumulusClips',
							'softname' => 'cumulus',
							'desc' => 'CumulusClips Free Video Sharing CMS, Video Sharing Script, Video Sharing Software, YouTube Clone.',
							'ins' => 1,
							'cat' => 'video',
							'type' => 'php',
							'ver' => '1.3.2'
							),
				438 => array('name' => 'Bolt',
							'softname' => 'bolt',
							'desc' => 'Bolt Sophisticated, lightweight and simple CMS.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.6.9'
							),
				440 => array('name' => 'Dada Mail',
							'softname' => 'dada',
							'desc' => 'Dada Mail is a Contemporary Mailing List Manager.',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'perl',
							'ver' => '7.2.1'
							),
				441 => array('name' => 'Tiny Tiny RSS',
							'softname' => 'tinyrss',
							'desc' => 'Tiny Tiny RSS is an open source web-based news feed (RSS/Atom) reader and aggregator.',
							'ins' => 1,
							'cat' => 'rss',
							'type' => 'php',
							'ver' => '1.14'
							),
				442 => array('name' => 'webtrees',
							'softname' => 'webtrees',
							'desc' => 'webtrees is the web\'s leading on-line collaborative genealogy application.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.6.0'
							),
				443 => array('name' => 'Croogo',
							'softname' => 'croogo',
							'desc' => 'Croogo is a free, open source, content management system for PHP, released under The MIT License.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.1.1'
							),
				444 => array('name' => 'Little Software Stats',
							'softname' => 'lss',
							'desc' => 'Little Software Stats is a web application that allows users to monitor their software.',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '0.1'
							),
				445 => array('name' => 'Open Real Estate',
							'softname' => 'realestate',
							'desc' => 'Open Real Estate s a free software for building websites of real estate agencies and realtors.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.9.1'
							),
				446 => array('name' => 'Commentics',
							'softname' => 'commentics',
							'desc' => 'Commentics is a free, advanced PHP comment script with many features.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.5'
							),
				448 => array('name' => 'X2CRM',
							'softname' => 'x2',
							'desc' => 'X2CRM is an open source based Sales, Marketing Automation and Service application designed exclusively for companies that require a tightly focused customer information system.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '4.3'
							),
				449 => array('name' => 'Admidio',
							'softname' => 'admidio',
							'desc' => 'Admidio is a free online membership management, optimized for clubs, groups and organizations.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.4.8'
							),
				450 => array('name' => 'Open Source Point of Sale',
							'softname' => 'ospos',
							'desc' => 'Open Source Point of Sale is a point of sale system built on top of a CodeIgniter base.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2.3'
							),
				451 => array('name' => 'iGalerie',
							'softname' => 'igalerie',
							'desc' => 'iGalerie represents a paradigm shift in how the personal academic and research web sites are created and maintained.',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '2.3.4'
							),
				452 => array('name' => 'webERP',
							'softname' => 'weberp',
							'desc' => 'webERP is a complete web based accounting/ERP system that requires only a web-browser and pdf reader to use.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '4.11.3'
							),
				453 => array('name' => 'DHTMLX',
							'softname' => 'dhtmlx',
							'desc' => 'DHTMLX Suite JavaScript Component Library for Building Rich Web Apps.',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '4.0'
							),
				455 => array('name' => 'Privacy Policy Generator',
							'softname' => 'policy',
							'desc' => 'Privacy Policy Generator is a free generator that lets you generate a privacy policy agreement for your site in minutes.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.0'
							),
				457 => array('name' => 'HelpDEZk',
							'softname' => 'helpdezk',
							'desc' => 'HelpDEZk is a powerfull software that manages requests/incidents.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.0.1'
							),
				458 => array('name' => 'XCloner',
							'softname' => 'xcloner',
							'desc' => 'XCloner is a professinal backup and restore application designed for PHP/Mysql websites',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '3.5'
							),
				460 => array('name' => 'Group Office',
							'softname' => 'goffice',
							'desc' => 'Group Office is complete online groupware.',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '5.0.89'
							),
				462 => array('name' => 'pH7CMS',
							'softname' => 'hizup',
							'desc' => 'pH7CMS The First and Best Social Dating Open Source Site.',
							'ins' => 1,
							'cat' => 'socialnetworking',
							'type' => 'php',
							'ver' => '1.1.2'
							),
				463 => array('name' => 'Blesta',
							'softname' => 'blesta',
							'desc' => 'Blesta Automatically Invoice &amp; Manage Clients With Ease.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '3.3.1'
							),
				464 => array('name' => 'AngularJS',
							'softname' => 'angular',
							'desc' => 'AngularJS HTML enhanced for web apps!',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '1.2.26'
							),
				465 => array('name' => 'Magento 1.7',
							'softname' => 'magento17',
							'desc' => 'Ecommerce platform for growth',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.7.0.2'
							),
				466 => array('name' => 'SiteDove',
							'softname' => 'sitedove',
							'desc' => 'SiteDove Free is a powerful tool for beefing up the security of your website at NO COST.',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '6'
							),
				467 => array('name' => 'Webasyst',
							'softname' => 'webasyst',
							'desc' => 'Webasyst is a suite of web apps that helps people work together in teams, collaborate, build websites and online stores - all in one place.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '1.2.3'
							),
				468 => array('name' => 'LiteCart',
							'softname' => 'litecart',
							'desc' => 'LiteCart is a new innovative free shopping cart platform developed in PHP.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.1.2.1'
							),
				469 => array('name' => 'Loaded 7',
							'softname' => 'loaded7',
							'desc' => 'Loaded 7 is a responsive ecommerce web application.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '7.002.5.0'
							),
				470 => array('name' => 'Ghost',
							'softname' => 'ghost',
							'desc' => 'Ghost is an Open Source application which allows you to write and publish your own blog',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '0.5.3'
							),
				471 => array('name' => 'UIkit',
							'softname' => 'uikit',
							'desc' => 'UIkit A lightweight and modular front-end framework for developing fast and powerful web interfaces.',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.11.0'
							),
				473 => array('name' => 'Symfony',
							'softname' => 'symfony24',
							'desc' => 'Symfony is aimed at building robust applications in an enterprise context',
							'ins' => 1,
							'cat' => 'frameworks',
							'type' => 'php',
							'ver' => '2.5.6'
							),
				474 => array('name' => 'Sitemagic CMS',
							'softname' => 'sitemagic',
							'desc' => 'Sitemagic CMS is a lightweight yet very capable Content Management System.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '20131030'
							),
				475 => array('name' => 'Open eShop',
							'softname' => 'openeshop',
							'desc' => 'Open eShop allows you to start selling any digital good, like MP3, eBooks, Movies, Software.. or any Service you offer.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.6.1'
							),
				476 => array('name' => 'ProcessWire',
							'softname' => 'procwire',
							'desc' => 'ProcessWire is a free PHP5 content management system and framework (open source CMS/CMF) built to save you time and work the way you do.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.5.2'
							),
				477 => array('name' => 'wallabag',
							'softname' => 'wallabag',
							'desc' => 'wallabag is a read-it later application. You can use it to save a link (including all content : text, images, videos).',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.8.0'
							),
				478 => array('name' => 'ClientExec',
							'softname' => 'clientexec',
							'desc' => 'ClientExec offers online help desk software intended to enhance the ability of small and mid-sized hosting businesses to manage help and support issues.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '5.1.3'
							),
				479 => array('name' => 'CS-Cart',
							'softname' => 'cscart',
							'desc' => 'CS-Cart is the best shopping cart solution for building an ecommerce website of any size: from a small web store to a virtual shopping mall.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '4.2.3'
							),
				480 => array('name' => 'SiteCake',
							'softname' => 'sitecake',
							'desc' => 'Simple, drag and drop CMS for fast editing',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '1.0.41'
							),
				481 => array('name' => 'Jamroom',
							'softname' => 'jamroom',
							'desc' => 'Jamroom is a community content management system. It enables you to bring your entire community online to participate in your websites content creation.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '5.2.12'
							),
				482 => array('name' => 'Monsta FTP',
							'softname' => 'monsta',
							'desc' => 'Monsta FTP Open source PHP/Ajax cloudware that puts FTP file management right in your browser, anywhere, any time. ',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.4.6'
							),
				483 => array('name' => 'Live helper chat',
							'softname' => 'livehelper',
							'desc' => 'Live helper chat is Free & Flexible & Open source - Live Support chat for your website.',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.13'
							),
				485 => array('name' => 'Moodle',
							'softname' => 'moodle27',
							'desc' => 'Moodle is a Course Management System',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.7.2'
							),
				486 => array('name' => 'Magento 1.8',
							'softname' => 'magento18',
							'desc' => 'Ecommerce platform for growth',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.8.1.0'
							),
				488 => array('name' => 'Shopware',
							'softname' => 'shopware',
							'desc' => 'Shopware is a highly flexible, powerful and customizable software solution that allows you to quickly and easily create an online shop, regardless of your store requirements.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '4.3.2'
							),
				489 => array('name' => 'Thelia 2',
							'softname' => 'thelia',
							'desc' => 'Thelia E-commerce solution based on Symfony 2.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2.0.4'
							),
				490 => array('name' => 'SeoToaster Ecommerce',
							'softname' => 'toaster',
							'desc' => 'SeoToaster E-commerce is the most advanced SEO CMS & Ecommerce web site builder.',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2.3.0'
							),
				491 => array('name' => 'Invoice Ninja',
							'softname' => 'ninja',
							'desc' => 'Invoice Ninja THE SIMPLE & FREE WAY TO INVOICE CLIENTS',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.5.1'
							),
				492 => array('name' => 'SuiteCRM',
							'softname' => 'suitecrm',
							'desc' => 'SuiteCRM is a free and open source alternative to SugarCRM Professional Edition',
							'ins' => 1,
							'cat' => 'erp',
							'type' => 'php',
							'ver' => '7.1.4'
							),
				494 => array('name' => 'InfiniteWP',
							'softname' => 'iwp',
							'desc' => 'InfiniteWP is a free, self-hosted multiple WordPress management platform that simplifies your WordPress management tasks into a simple click of a button.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.4.0'
							),
				498 => array('name' => 'Concrete5 5.6',
							'softname' => 'conc56',
							'desc' => 'Concrete5 makes running a website easy.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '5.6.3.2'
							),
				499 => array('name' => 'OpenCart',
							'softname' => 'ocart2',
							'desc' => 'The Super Cool Ecommerce Solution',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '2.0.0.0'
							),
				500 => array('name' => 'SeoToaster CMS',
							'softname' => 'toastercms',
							'desc' => 'SeoToaster CMS is the most advanced SEO CMS.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.3.0'
							)
			);

?>